### ISSUE TITLE
[EPOS] Oversikt over datasett og datatjenester

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#1]
Som tjenesteutvikler
ønsker jeg oversikt over datasett og datatjenester som offentlig, privat og frivillig sektor tilbyr, 
slik at jeg kan få oppdage, vurdere og ta i bruk data(tjenester) som allerede eksisterer 

------------------
Tilknyttede brukerhistorier:

Lenke til trådskisser:
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Levert ved "Finn data" inngang på Datafabrikken
