### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til kriminalitetsstatistikk på granulært format

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#10]
Som tenesteutviklar,
ønskjer eg tilgang til kriminalitetsstatistikk på granulært format 
så eg kan tilby mine brukarar informasjon om kriminalitet i eit område.

------------------

Relatert til epos: #6

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Ei historie frå Chicago om opning av kriminalitetsstatistikk:
https://beyondtransparency.org/chapters/part-1/open-data-in-chicago-game-on/
Dei nemner blant anna korleis dei gjorde data meir anonyme (oppgje på kvartalsnivå i staden for spesifikke adresser).

**Comment by oystein-asnes** [comment]
Lukkes. Er knyttet til konkrete case. Erstattes av generiske behovsbeskrivelser.
