### ISSUE TITLE
[BRUKERHISTORIE] Google Analytics for Datalandsbyen

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#100]
Som: forvalter av Datalandsbyen
Ønsker jeg å: få statistikk for besøk på tvers av integrasjoner
Slik at: jeg får besøksstatistikk samlet

------------------

Relatert til epos:
Bygger videre på #71 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
1. Datafabrikken brukte Universal Analytics. Google Analytics 4 er anbefalt siden UA skal fases ut etterhvert. Har derfor endret til GA4. UA samler ikke statistikker lenger.
2. Datalandsbyen sidene på datafabrikken sender statistikker til både datafabrikken og datalandsbyen (page hits)
3. Datalandsbyen bruker GA4 fra før.

**Comment by livarb** [comment]
Flott! Ser at det kjem trafikk inn i Google Analytics frå begge nettstadane.
Det er uklårt for meg korleis ein kan få rapporter på sidevisningar pr. emne/post på tvers av nettstadar. Har laga ei ny sak på dette, #116
