### ISSUE TITLE
[BRUKERHISTORIE] Nasjonalt ressurssenter for deling av data inn i Datalandsbyen

### ISSUE THREAD

**Issue by Den-sortesvane** [datadeling/behov-issue-tracker#102]
Som: Datafabrikken
Ønsker jeg å: få synliggjort nasjonalt ressurssenter for deling av data i datalandsbyen
Slik at: brukere enklere kan komme i kontakt og bruke senteret

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

**Comment by livarb** [comment]
@LeneSundsbo : Eit lite design-oppdrag i forbindelse med dette. Vi treng eit ikon for den nye kategorien. Sjå korleis det er i stagingmiljøet. Der har eg foreløpig berre valgt eit ikon frå ikon-biblioteket som er i plattformen. Ser ut som at dei andre kategoriane har skreddarsydde ikon. Kan det stemme?

**Comment by livarb** [comment]
Ressurssenteret er på plass med ny kategori og ikon:
![image](https://user-images.githubusercontent.com/3617256/143831300-97b50c56-7f22-4eb7-8559-e38ad77f072c.png)
