### ISSUE TITLE
[BRUKERHISTORIE] Videreutvikle kontaktsidene

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#103]
Som: interessert i datafabrikken (potensiell partner, konsument, tilbyder eller presse/media)
Ønsker jeg å: få informasjon om hvordan jeg kan kontakte datafabrikken for akkurat mitt ærend  
Slik at: jeg føler meg oppmuntret til å ta kontakt, at min forespørsel kommer på riktig sted og at jeg eventuelt kan bli kontaktet av datafabrikken

------------------

Personas/brukergrupper som kan ha dette behovet:
* Media som trenger en pressekontakt
* Virksomheter som vil inngå partnerskap 
* Potensielle datakonsumenter
* Potensielle datatilbydere
* På sikt: Brukere som vil gi innspill til løsning

Aktuelle virkemidler/kanaler: Datalandsbyen, github, epostlister mv

Relatert til epos: #79 

[Lenke til design for desktop](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/contact-d.html)
[Lenke til design for mobil](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/contact-m.html)
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by palunanue** [comment]
Kontaktsidene i dag er veldig ad hoc laget og trenger ny struktur. I hovedsak er "Kontakt oss"-sider ofte en catch-all for de som ikke klarer å finne informasjon et annet sted. Problemet med at datatilbydere / -konsumenter ikke klarer å finne informasjon om disse temaene, må først og fremst løses på andre steder enn kontakt oss-siden. I behovskømøte 07 okt 21 skisserte jeg en kontakt oss-side der behovet rutes gjennom opp til tre ulike valg, i form av opptil tre bokser. Presse er en av dem, og noe som alltid er på kontakt oss-sider for store organisasjoner. Hva de to andre boksene er, kan diskuteres men "Andre henvendelser" og en videresending til en generell mottaksadresse er nok et minimumskrav.

**Comment by palunanue** [comment]
Som vi snakket om i standup fre 15 okt, kan vi kutte ut adressene som står nederst på Kontakt oss, og som går til spesifikke personer i datafabrikken. Som hovedregel skal kontakt oss-lenker være upersonlige. Dersom feks en datatilbyder eller datakonsument ønsker å komme i kontakt med oss, bør denne kontakt-oss-siden være en absolutt siste nødløsning, som et resultat av at de ikke har funnet nok info på tjenestesidene. Spesifikk kontaktinfo til de ulike tjenestene bør også være på tjenestesidene, ikke på kontakt-oss-siden. 

Ønske for design på denne siden: Tre bokser under teksten på midten. 

1. Første boks kan være "Generelle henvendelser" og gå til datafabrikken@norge.no med forhåndssatt emne "Henvendelse via datafabrikken.norge.no". 
2. Andre boks kan være "Partnerhenvendelse" og gå til Helges eller Mortens epost. Dersom @helgedahljor mener denne bør være noe annet er det helt innafor. 
3. Tredje boks kan være Mediehenvendelse og gå til pal.unanue-zahl@digdir.no foreløpig, med forhåndssatt emne: Mediehenvendelse til datafabrikken

Listen under med eposter kan tas vekk ved publisering av ny versjon på siden.
