### ISSUE TITLE
[BRUKERHISTORIE] Profilside for datatilbydere

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#104]
Som: datatilbyder
Ønsker jeg å: profilere min virksomhet og de data-relevante tjenestene vi tilbyr
Slik at: vi øker synligheten for virksomhetens data for potensielle konsumenter

------------------

Relatert til epos: #79 #12 

Lenke til design: https://christianmellbye.wixsite.com/datafabrikken/vision 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by Den-sortesvane** [comment]
https://christianmellbye.wixsite.com/datafabrikken/vision <-- Håper lenken fungerer.

**Comment by oystein-asnes** [comment]
Prioriteres ikke nå. Løses (delvis) av #105 i form av en virksomhetsside i selve datasettkatalogen.
