### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til data om infrastruktur-prosjekt og innverknade på reisetid

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#11]
Som tenesteutviklar,
ønskjer eg tilgang på data om infrastruktur-prosjekt og innverknad på reisetid 
slik at eg kan nytte dette til å berekne framtidig reisetid mellom to punkt

------------------

Relatert til epos: #6 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Lukkes. Er knyttet til konkrete case. Erstattes av generiske behovsbeskrivelser.
