### ISSUE TITLE
[BRUKERHISTORIE] Kortere vei til kommentering fra detaljvisning av datasett

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#112]
Som: bruker av datakatalogen
Ønsker jeg å: enkelt kunne kommentere på et datasett direkte i detaljvisningen i katalogen
Slik at: jeg slipper å skifte kontekst for å kommentere

------------------
Nåsituasjon:
Når jeg skal kommentere på et datasett som ikke tidligere er kommentert i datalandsbyen må jeg i dag gjøre følgende når jeg står i detaljvisning:
1. følge lenken til datalandsbyen
2. velge en kategori (jeg skal kommentere på datakvaliteten, så ingen fremstår som relevante men jeg velger "tips og spørsmål"
3. jeg må opprette et nytt emne
4. jeg må tilbake til datakatalogen (data.norge, datafabrikken eller transportportalen) og finne lenken til datasettet jeg skal kommentere på
5. jeg må legge inn lenken som hyperlenke i innlegget mitt og publisere. 

Ønsket situasjon/løsningsforslag:
1. datasettet har et åpent kommentarfelt (eller kommentér-knapp) som jeg kan benytte til å legge igjen min kommentar direkte. 
2. dersom jeg ikke er innlogget i datalandsbyen blir jeg bedt om å gjøre dette (uten å miste kontekst). 

Nødvendige avklaringer:
1. Skal første kommentar starte et nytt emne? 
2. Skal tittelen på emnet være predefinert eller brukerdefinert?
3. I detaljvisningen: Skal andre kommentar være svar til første tråd, eller nytt emne? Skal brukeren kunne velge dette?
4. Hvilke kategori skal benyttes?  "Tips og spørsmål"? Tilbakemeldinger og brukerkommentarer kan også være andre ting.   

Relatert til epos: #71 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Konklusjoner 10.12.2021:

- Kommentar er noe annet enn forumpost
- Skjult i datalandsbyen
- Det kan være behov for å svare på en kommentar
- Kontakt med tilbyder skjer manuelt eller semi-automatisk der det finnes en e-postadresse
- Må kunne lese hele kommentaren

**Comment by VeronikaWalnum** [comment]
Gjennomgang 17.01.22
Gjenstående fiks/oppgaver kommentar:
- Mobilstrls - Mats og Lene 
- Kommentartråd skal ikke ligge synlig under Datalandsbyen? Dette er en innstilling i Datalandsbyen. Vi kan starte med å ha den synlig, fjerne hvis behov. Kan endre trådnavnet til noe kortere, da er det også mer plass til kommentarteksten.
- Markdown - få inn resterende aktuelle
- Får vi previewvisning kun? (ikke markdownvisning)
- Slette og editere - kun egne innlegg (+admin kan slette og editere gjennom Datalandsbyen) Hvis sletter en kommentar så skal evt svar i tråd under også bli borte
- Spamhåndtering? Datalandsbyen har noe. Vi legger ikke opp til noe mer.
- Skal bolken med Datalandsbyen legges over kommentar?
- Oppfølging av spm/kommentar: hvordan rigger vi oss? Vi må sørge for at vi følger opp det som kommer inn av spm. Kan følge opp varsling på kategorien pr e-post. Evt. RSS. Er det mulig å få en kanal i Slack? Hvem har hovedansvaret.
- Skal vi legge inn noen kommentarer selv for å dra i gang aktiviteten? :)

**Comment by livarb** [comment]
Lanseringsplan - stikkord etter diskusjon på behovsstandup tidlegare i dag:
- Datatilbyderar i data.norge.no/FDK skal få e-post om denne nye funksjonaliteten i god tid før den vert lansert. Livar følgjer opp.
- Vi legg ein plan for å kunngjere og spre ordet (SoMe, Digdir sine kanalar etc.)
- Får på plass ny underkategori i Datalandsbyen for nytt i Felles datakatalog der vi legg inn ein post ved lanseringa og skriv meir i detalj.
