### ISSUE TITLE
[BRUKERHISTORIE] Enklere og mer konsistent referering fra datalandsbyen til ressurser i datakatalogen

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#113]
Som: bruker av datalandsbyen
Ønsker jeg å: enkelt kunne referere til ressurser i datakatalogen
Slik at: min omtale blir vist som brukergenererte metadata til ressursene jeg omtaler i katalogen

------------------

Relatert til epos: #71 

Dette er mulig i dag ved å hyperlenke til ressursen i katalogen. For å gjøre det ennå enklere kan en utvikle en søkewidget (med autoforslag) som gjør oppslag i katalogen direkte fra inputkjemaet i datalandsbyen (omtrent på samme måte som en relaterer begreper til datasett i reg. skjemaet) slik at brukeren slipper å gå ut av kontekst (finne lenken i katalogen og så gå tilbake å legge denne til som lenke). 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
@oystein-asnes Løsningen er nå prodsatt
