### ISSUE TITLE
[BRUKERHISTORIE] Feil i tekst-formatering i Datalandsbyen i Datafabrikken

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#115]
Linjeskift vert vist feil, så postane ser rotete ut i visninga i Datafabrikken.

Eksempel
https://datalandsbyen.norge.no/topic/97/turbo-nettlesar-plugin-for-datahotellet
https://datafabrikken.norge.no/datalandsbyen/2/gode-eksempler-p%C3%A5-bruk/97/turbo-nettlesar-plugin-for-datahotellet

![image](https://user-images.githubusercontent.com/3617256/141443339-47159968-1144-4dd9-a56f-a4838d18ab55.png)
![image](https://user-images.githubusercontent.com/3617256/141443380-3a9df48c-666a-4e84-a9a4-689af35d4c3d.png)

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Det er kanskje meir presist å seie at det er feil ved visning av paragrafar, heller enn linjeskift.

**Comment by shenluna** [comment]
Issue moved to [datadeling/datafabrikken-portal #105](https://github.com/datadeling/datafabrikken-portal/issues/105) via [**ZenHub**](https://www.zenhub.com/)
