### ISSUE TITLE
[BRUKERHISTORIE] Mellomside for veiledning

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#123]
Som: bruker av portalen
Ønsker jeg å: få oversikt over veiledere ut fra min rolle som enten tilbyder eller konsument
Slik at: jeg får den hjelpen jeg trenger

------------------

Relatert til epos: #79 

Lenke til design:
Lenke til løsningsarkitektur: Kladd; https://miro.com/app/board/o9J_lcZhdpo=/?moveToWidget=3458764514205270808&cot=14

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by Den-sortesvane** [comment]
Gir vi nok veiledning før de kommer inn i selve "produktet" ? Forslag til løsning for SSB: 
"SSB har jevnlig kurs i hvordan man kan koble seg til åpen APIer. Her kan du se siste webinar som gir opplæring i bruk av disse APIene."
