### ISSUE TITLE
[BRUKERHISTORIE] Kurs og veiledningskatalog

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#124]
Som: bruker av datafabrikkens nettsider
Ønsker jeg å: få oversikt over anbefalte kurs og veiledere
Slik at: raskt finner det jeg trenger

------------------

Løsningsforslag: Malstyrt katalog over alle kurs og veiledere (og standarder og spesifikasjoner?), med et kontrollert vokabular som gjør det mulig å vise ulike delmengder på relevante undersider. Visningen er tenkt som "kort" på samme måte som her: https://datafabrikken.norge.no/nyttige-kurs 

### Informasjonselementer - kurs:

- [x] katalogkort-bilde*
- [x] tittel*
- [x] beskrivelse*
- [x] lenke til ressurs*
- [ ] ~~type ressurs* (envalg):  `kurs`, `veileder`~~
- [x] undertype ressurs: (envalg)**Kurs**:  `introkurs`, `dybdekurs`,  `etter- og videreutdanning` 
- [x] Primærmålgrupper (envalg): `datatilbydere`, `datakonsumenter`, 
- [x] tidsangivelse i minutter
- [x] antall moduler
- [x] gratis `ja`, `nei
- [x] Tilbyder m/logo ("Leveres av `kontrollert liste` og `logo`
- [ ] Språk (norsk/engelsk)
- [ ] Studiepoeng
- [ ] Vekting? (noe som styrer rekkefølge i visning)

### Informasjonselementer - veileder:
- [x] katalogkort-bilde*
- [x] tittel*
- [x]  beskrivelse*
- [x] lenke til ressurs*
- [x] Primærmålgrupper (envalg): `datatilbydere`, `datakonsumenter`, 
- [x] tidsangivelse i minutter
- [ ] Tilbyder m/logo ("Leveres av `kontrollert liste` og `logo`
- [ ]  Språk (norsk/engelsk)
- [ ] Vekting? (=noe som styrer rekkefølge i visning)
- [ ] Type ressurs: tekst, video, tekst og video

Relatert til epos: #146

Lenke til design: https://datafabrikken.norge.no/kurs  
Lenke til løsningsarkitektur: 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Eksempel på kurskatalog: https://norwegiancognitivecenter.com/blog/increase-your-competence

**Comment by livarb** [comment]
Dette høyrest ut som det også er eit datasett å putte i datakatalogen?

**Comment by oystein-asnes** [comment]
Har oppdatert beskrivelsen og lagt til språk som nytt element @jeffreiffers . Er fortsatt litt usikker på om kurs og veiledere skal være to ulike collection types.

**Comment by oystein-asnes** [comment]
Lukkes. Vekting løses i #157
