### ISSUE TITLE
[BRUKERHISTORIE] Måling av metadatakvalitet: tilgjengelighet

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#127]
Som: tilbyder av data i datakatalogen
Ønsker jeg å: få vurdering av kvaliteten på mine datasetts tilgjengelighet
Slik at: jeg kontinuerlig kan forbedre egen metadatakvalitet

------------------

> Accessible (https://www.go-fair.org/fair-principles/) 
> Once the user finds the required data, she/he/they need to know how can they be accessed, possibly including authentication and authorisation.
> 
> - A1. (Meta)data are retrievable by their identifier using a standardised communications protocol
>  &nbsp; A1.1 The protocol is open, free, and universally implementable
>  &nbsp; A1.2 The protocol allows for an authentication and authorisation procedure, where necessary
> - A2. Metadata are accessible, even when the data are no longer available

Datasett kan gjøres tilgjengelig som distribusjoner og/eller datatjenester. Tilgjengelighet treffer begge disse, så distribusjoner og datatjenester må ses på i sammenheng. Forslag til indikatorer:

1. dcat:distribution er oppgitt (=det eksisterer en eller flere distribusjoner)
2. dcat:accessURL er oppgitt OG tilgjengelig (obligatorisk for `dcat:Distribution`) [dersom lenkesjekk feiler, gis det ikke uttelling]
3. dcat:downloadURL er oppgitt OG tilgjengelig (valgfri for `dcat:Distribution`) [dersom lenkesjekk feiler, gis det ikke uttelling]
4. dcat:accessService er oppgitt (valgfri for `dcat:Distribution`) [skal være lenke til en datatjeneste i API-katalogen]
5. dcat:endpointURL er oppgitt (obligatorisk for `dcat:Dataservice`)
6. dcat:servesDataset er oppgitt (anbefalt for `dcat:Dataservice`)

2 og 3 kan en vurdere å splitte i to (oppgitt og tilgjengelig). Eventuelt droppe lenkesjekk.

På avstand kan det se ut som dette favoriserer de som tilbyr åpne data, men tilbydere av data som ikke er allment tilgjengelig kan likevel tilby eksempeldata (Datasett: adms:sample) for nedlasting.  Eksempeldata oppgis i klassen datasett og har range dcat:distribution. Vi skiller ikke her på om det er "ekte data" eller eksempeldata som gjøres tilgjengelig. 

`dcat:servesDatasett` `dcat:accessService` er litt to sider av samme sak, men det er ikke samme relasjon. It's complicated..., men foreslår altså å gi poeng for begge. 

Format/mediatype er ikke med her, se egen brukerhistorie for interoperabilitet

Relatert til epos: #126 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by jeffreiffers** [comment]
Skal alle poeng fordeles blant disse 6. Mao 16,7% per punkt eller veier noen tyngre en andre? 16,6666667 er heller ikke så enkelt å regne med.

**Comment by oystein-asnes** [comment]
Second thoughts: Det er kanskje litt meningsløst å gi poeng for punkt 1. Å opprette en distribusjon uten `dcat:accessURL` gir ingen mening/verdi. Dersom vi dropper å gi poeng her, så blir det enklere å fordele flatt (20% på hver).

**Comment by oystein-asnes** [comment]
Realiseres gjennom #138
