### ISSUE TITLE
[BRUKERHISTORIE] Stemming av søkeord

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#129]
Som: bruker av tjenesten "finn data"
Ønsker jeg hjelp til å komme meg videre når jeg benytter feil søkeord 
Slik at jeg ikke får null resultater

------------------
Relatert til brukerhistorie: #85 
Testkriterie: Når jeg søker på "mattabell" skal jeg få treff i matvaretabell.

Relatert til epos: #84 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
At søk på «mattabell» gir treff på «matvaretabell» trur eg er ei meir avansert form for stemming/søk. Stemming er vanlegvis å redusere ord til rotform, f.eks. «matvaretabeller» --> «matvaretabell». Usikker på kva støtte for slik som finst i ElasticSearch.
https://www.elastic.co/guide/en/elasticsearch/reference/current/stemming.html

**Comment by oystein-asnes** [comment]
Erstattes av https://github.com/Informasjonsforvaltning/behov/issues/751
