### ISSUE TITLE
[BRUKERHISTORIE] Endre metadata-kriterier: "søkbarhet" og "lesbarhet"

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#131]
Som: datatilbyder
Ønsker jeg å: vite i hvor stor grad mine data er i tråd med FAIR-prinsippene
Slik at: jeg kan bli en bedre datatilbyder

------------------

 Lesbarhet er et litt hjemmesnekret kriterium som vi kan vurdere å slå sammen med `Søkbarhet`. 

 (NB: "Begrep er oppgitt" er litt stammespråk? Endre til "sentrale dataelementer er definert?") 

Relatert til epos: #126 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Må vurderes i realiseringen av #138

**Comment by shenluna** [comment]
Flyttet til informasjonsforvaltning, https://github.com/Informasjonsforvaltning/behov/issues/730
Lukker denne.
