### ISSUE TITLE
[BRUKERHISTORIE] Måling av metadatakvalitet i samsvar med data.europa.eu

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#138]
Som: tilbyder av data
Ønsker jeg å: vite noe om kvaliteten på beskrivelsene jeg tilbyr
Slik at: jeg kan forbedre kvaliteten på virksomhetens datakatalog

------------------
EUs måling: https://data.europa.eu/mqa/methodology?locale=en

[Gapanalyse-metadatakvalitet.xlsx](https://github.com/datadeling/behov-issue-tracker/files/7895194/Gapanalyse-metadatakvalitet.xlsx)

Relatert til epos: 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Flyttet til informasjonsforvaltning, https://github.com/Informasjonsforvaltning/behov/issues/729, lukker denne.
