### ISSUE TITLE
[BRUKERHISTORIE] Sette opp konverteringsmål i Google analytics

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#145]
Som: tilbyder av tjenesten Datafabrikken
Ønsker jeg å: definere og måle vellykkede besøk på siden
Slik at: jeg kan vite noe om utviklingen over tid knyttet til brukervennlighet og opplevd relevans for brukerne 

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Kan vi lukke denne @palunanue ? Gjerne med ein kommentar om kva som er gjort.

**Comment by palunanue** [comment]
Ja den kan lukkes. det er satt opp rapporter som langt på vei måler dette. Her: https://datastudio.google.com/u/0/reporting/875da855-f4ee-4ced-8b2c-4f0860f5c5fc/page/P6AvC
