### ISSUE TITLE
[BRUKERHISTORIE] Søk i Datalandsbyen i Datafabrikken

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#148]
Som: bruker av Datalandsbyen i Datafabrikken
Ønsker jeg å: kunne søke
Slik at: jeg kan finne poster med innhold jeg leter etter

------------------

Relatert til epos: #71 

Lenke til design: https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-d.html (klikk på søkefeltet)
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

I dag er det ikke noe søkefelt i Datafabrikken:
![image](https://user-images.githubusercontent.com/3617256/155311523-b6c48541-5859-472e-a5d2-ab745b1ada24.png)

Se også #134

**Comment by shenluna** [comment]
Forslag til design på søkeresultat https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-search-d.html

**Comment by livarb** [comment]
> Forslag til design på søkeresultat https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-search-d.html

Det ser veldig bra ut.

Foreslår vi droppar å vise emneord.

Kva skjuler seg bak «Vis avansert søk», forresten?

**Comment by shenluna** [comment]
> > Forslag til design på søkeresultat https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-search-d.html
> 
> Det ser veldig bra ut.
> 
> Foreslår vi droppar å vise emneord.
> 
> Kva skjuler seg bak «Vis avansert søk», forresten?

Enig at vi kan droppe emneord.

Vis avanser søk er noe innebygget i Datalandsbyen, usikker på om det er nødvendig å ha det med.
![image](https://user-images.githubusercontent.com/73637969/159931833-01c1657f-d336-4f38-8567-dc058ab87904.png)

I første omgang tenker jeg at det ikke er nødvendig. Så kan man heller se på å legge det til hvis man ser at det blir brukt i Datalandsbyen.

**Comment by livarb** [comment]
Enig i at avansert søk ikkje er noko vi treng i første omgang.

**Comment by livarb** [comment]
@LeneSundsbo : Treng du noko meir frå oss utover innspela over?

**Comment by LeneSundsbo** [comment]
@livarb Nei, har det jeg trenger i denne omgang. Glemte å lime inn lenke til design, den er nå på plass i saken.

Til info viser skisse kun søkefelt og design for søketreffliste. Knapp for avansert søk er ikke klikkbar da jeg ikke skal redesigne avansert søk i denne omgang (forhåpentligvis senere).

**Comment by livarb** [comment]
@LeneSundsbo : Aha. Så «Vis avansert søk» er berre med i skissa for ei sak i framtida?
Kanskje like greitt å fjerne frå skissa for no så ein ikkje heng seg opp i det i denne saka?

**Comment by LeneSundsbo** [comment]
@livarb Her må kanskje @shenluna på banen for å bekrefte om det stemmer at vi **benytter avansert søk** (derav knapp) slik det eksisterer i Datalandsbyen i dag, og at vi **ikke prioriterer redesign** av det avanserte søket nå.

**Comment by livarb** [comment]
@LeneSundsbo : Min tanke bak å foreslå å kutte ut heile det avanserte søket i denne omgang, var at det ville ta mykje tid å implementere i DL-DF-front-end. Om det ikkje er tilfelle, tenker eg vi kan ta det med.
@shenluna : har vi eit guesstimate på kor arbeidskrevjande det er å ta med avansert søk?

**Comment by livarb** [comment]
Søket ser bra ut. Eg ser det kun gir treff i tittel. Søket må gje treff i både tittel og innhald.
Går det an å få markert treff i søkeresultatet? Jamfør designskisse

**Comment by shenluna** [comment]
@livarb Det var først implementert med treff i både tittel og innhold, men vi endret det til tittel da det er det man får som treff i Datalandsbyen. Jeg tenker søkeresultatet bør være likt begge steder.
Når det gjelder markering i treff er det mulig å gjennomføre, men det vil kreve en større jobb, det er dessverre ikke noe man får fra API-et til Node BB.

**Comment by livarb** [comment]
Vi snakka om dette på behovsstandup i dag. Oppsummert:
- Vi endrar til å søke i både titlar og innlegg
- Prøver å endre søket i Datalandsbyen til også å søke i både titler og innhald som standard.

Eg trudde det kanskje er ei innstilling i admin-panalet som måtte til for å endre søket i Datalandsbyen. Endra «Quick Search», som stod på berre "Titler", men det endra ikkje oppførselen på søket. Fann ikkje nokon andre innstillingar.
![image](https://user-images.githubusercontent.com/3617256/167083605-96aaf533-7804-402d-860d-72f74e48bb9e.png)

**Comment by shenluna** [comment]
@livarb søketreff er nå endret til å søke i både tittel og innlegg

**Comment by livarb** [comment]
Supert!
