### ISSUE TITLE
[BRUKERHISTORIE] Vise punktlister i innlegg i Datalandsbyen i Datafabrikken

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#150]
Som: bruker av Datalandsbyen i Datafabrikken
Ønsker jeg å: se kulepunkter i en post
Slik at: posten er bedre formatert og lettere å lese

------------------

Relatert til epos: #71 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Eksempel. Nederst i denne posten:
https://datalandsbyen.norge.no/topic/150/tilbud-om-solceller-ved-hjelp-av-bygningsdata-otovo

Her er kulepunkter:
![image](https://user-images.githubusercontent.com/3617256/155315041-d754e296-ee44-4704-b88f-916a99caea4d.png)

Men i visninga i Datafabrikken så vert dette ikkje vist som kulepunkt:
![image](https://user-images.githubusercontent.com/3617256/155315132-dab38cad-7f55-431d-9612-253069373aa3.png)
https://datafabrikken.norge.no/datalandsbyen/2/gode-eksempler-p%C3%A5-bruk/150/tilbud-om-solceller-ved-hjelp-av-bygningsdata-otovo

**Comment by livarb** [comment]
Er det meininga at kulepunkta skal vere til venstre for margen?
Tenker dei bør vere ut frå margen for resten av innhaldet. Gjerne med litt mindre innrykk enn i Datalandsbyen (sjå skjermbilde over)
![image](https://user-images.githubusercontent.com/3617256/160558466-0bf676e8-7f10-41bd-96f1-7b21ff5a5d85.png)

**Comment by LeneSundsbo** [comment]
Nei, punktlista skal ikke stikke utenfor margen. I [denne skissen](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/guide-provide-d.html) vises eksempel på punktliste, den ser slik ut:

<img width="746" alt="Screenshot 2022-04-11 at 09 24 38" src="https://user-images.githubusercontent.com/25385497/162685800-6cd4de98-4104-44df-bec6-b9ef306d7b36.png">

**Comment by livarb** [comment]
@LeneSundsbo : Godt å høyre det ikkje er meininga.
Ser i staging at dette ser ut til å vere retta. Ser det er ein PR som skal rette det, ref. https://github.com/datadeling/datafabrikken-portal/issues/175
![image](https://user-images.githubusercontent.com/3617256/162687211-d6016725-0f16-4689-8545-c057f961f7c8.png)

**Comment by shenluna** [comment]
@livarb @LeneSundsbo
Punktlistene er nå rettet i både staging og prod, men ser den riktig ut nå, eller starter den for langt til høyre?
Se eksempelet i øverste post

**Comment by livarb** [comment]
Dette ser bra ut. Ser likt ut som i Datalandsbyen:
https://datafabrikken.norge.no/datalandsbyen/2/gode-eksempler-p%C3%A5-bruk/150/tilbud-om-solceller-ved-hjelp-av-bygningsdata-otovo
https://datalandsbyen.norge.no/topic/150/tilbud-om-solceller-ved-hjelp-av-bygningsdata-otovo

**Comment by LeneSundsbo** [comment]
@shenluna Det er unødvendig mye innrykk sammenlignet med det jeg har skissert. Rettes gjerne opp 😉
