### ISSUE TITLE
[BRUKERHISTORIE] Ikoner til underkategorier i Datalandsbyen

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#151]
Trenger ikoner til (nye) underkategorier i Datalandsbyen.
I dag har vi ingen underkategorier.
Ikoner trengs både til Datalandsbyen og i Datalandsbyen i Datafabrikken.

Nye underkategorier:
- Under "Tilbakemeldinger og nyheter"
  - Data.norge
  - Datalandsbyen
  - Datafabrikken

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Sjå foreløpig oppsett i staging.
Det kan vere vi kan bruke samme ikon for alle tre underkategoriane, sidan alle handlar om nyheter for den spesifikke løysinga.

**Comment by shenluna** [comment]
@livarb Jeg forsto det slik at det var diskutert og kommet frem til at det kun er subkategorier i Datalandsbyen som skal ha felles ikon. Ikon i bruk på subkategorier nå: https://drive.google.com/file/d/1iZSlbhV0wlrLkT0YFVWc2er9MaJuxjsD/view?usp=sharing

Subkategorier i Datafabrikken har ikke ikon i nåværende design.

**Comment by livarb** [comment]
@shenluna : Ja, stemmer. God løysing dette. Så slepp vi å ta ei runde med ikon-design for kvar ny underkategori.
