### ISSUE TITLE
Mulighet for påmelding til nyhetsbrev

### ISSUE THREAD

**Issue by palunanue** [datadeling/behov-issue-tracker#153]
Som: Bruker av, og interessert i, Datafabrikken
Ønsker jeg å: kunne melde meg på nyhetsbrev fra Datafabrikken
Slik at: jeg kan holde meg oppdatert på nyheter, nye funksjoner i Datafabrikken, caser og mer

**Comment by palunanue** [comment]
Embedkode til Nyhetsbrevet:
[embed.txt](https://github.com/datadeling/behov-issue-tracker/files/8232228/embed.txt)

**Comment by palunanue** [comment]
Mulige steder å melde seg opp på nyhetsbrevet: Forside, Om Datafabrikken, Footer og i Nyhetssakene.

**Comment by LeneSundsbo** [comment]
@palunanue – Her kan du se forslag til utforming:

Forside – [Desktop](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/home-d.html) • [Mobil](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/home-m.html)
Om Datafabrikken – [Desktop](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/about-d.html) • [Mobil](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/about-m.html)
Kontakt – [Desktop](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/contact-d.html) • [Mobil](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/contact-m.html)

**Comment by shenluna** [comment]
Akseptert av Pål
