### ISSUE TITLE
Oppdatere farge og skygge på bokser

### ISSUE THREAD

**Issue by LeneSundsbo** [datadeling/behov-issue-tracker#155]
**Mørke bokser**
Background-color: blue-48
Box-shadow (desktop): blue-56 50% transparency, 0px 12px 48px;
Box-shadow (mobile): blue-56 50% transparency, 0px 6px 24px;

**Lyse bokser**
Background-color: white
Box-shadow (desktop): blue-38 15% transparency, 0px 12px 48px;
Box-shadow (mobile): blue-38 15% transparency, 0px 6px 24px;

Fargekoder
blue-38: #566C99
blue-48: #384359
blue-54: #252933
blue-56: #1C2026

**Comment by LeneSundsbo** [comment]
Skygger ser riktig ut i staging nå 💪🏻

**Comment by jeffreiffers** [comment]
Lukker du saken?

**Comment by LeneSundsbo** [comment]
Tror vi er ferdig med denne nå 😆
