### ISSUE TITLE
[BRUKERHISTORIE] Vekting av veiledere og kurs

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#157]
Som: redaktør av nettsiden
Ønsker jeg å: styre rekkefølgen på ressursene for veiledning og kurs i portal
Slik at:  u know why... :-)

------------------

Relatert til epos: 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by jeffreiffers** [comment]
Denne kan lukkes. Implementert i https://github.com/datadeling/datafabrikken-portal/issues/186
