### ISSUE TITLE
[BRUKERHISTORIE] Siste kommentarer på framsida av data.norge.no

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#158]
Som: bruker av data.norge.no
Ønsker jeg å: se nyeste kommentarer
Slik at: jeg kan se hva som rører seg i kommentarfeltene

------------------

Relatert til : #112 

Lenke til design: https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Mogeleg løysing:
Foreslår eit nytt "område" på framsida av data.norge.no der ein ser dei 3 nyaste kommentarane, liknande dagens "Siste saker frå Datalandsbyen". Plasser den nye boksen rett over «Siste saker fra Datalandsbyen». Sørg for at innhald i kommentar-kategorien ikkje dukkar opp i «Siste saker fra Datalandsbyen»

**Comment by livarb** [comment]
Blokkene med innhald («Siste kommentarer», «Siste saker i Datalandsbyen» osv.) heng litt vel tett i saman, etter mi personlege meining. Opplever det nesten som ein samanhengande lang vegg av tekst.
Kan vi skilje dei meir? Til dømes med å ha tydelegare overskrift i kvar boks eller meir mellomrom? @LeneSundsbo @shenluna 
Skjermbilde frå skissa:
![image](https://user-images.githubusercontent.com/3617256/163953995-b5dc1d67-3aad-46be-81a2-75f7812c33fb.png)

**Comment by shenluna** [comment]
Denne brukerhistorien er flyttet til informasjonsforvaltning
