### ISSUE TITLE
[EPOS] Dynamisk juridisk veileder for deling av data

### ISSUE THREAD

**Issue by ttitland** [datadeling/behov-issue-tracker#164]
Som: eier av data
Ønsker jeg å: få enklere juridisk veiledning for deling av data
Slik at: jeg unngår å deler data jeg ikke har lov til å dele

------------------

Tilknyttede brukerhistorier:

Lenke til trådskisser:
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Denner er prod.sett. Lukkar saka.
