### ISSUE TITLE
[BRUKERHISTORIE] Dynamisk juridisk veiviser - få tilsendt svar som PDF

### ISSUE THREAD

**Issue by ttitland** [datadeling/behov-issue-tracker#166]
Som: bruker av den dynamiske juridiske veiviseren for deling av data
Ønsker jeg å: få tilsendt mine svar på PDF-format
Slik at: jeg har dokumentasjon på resultatene

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Losen har innebygget lagring av resultatet hvor man enten kan skrive det ut, eller lagre som PDF. Tilfredstiller dette kravene til brukerhistorien?

**Comment by livarb** [comment]
Ut frå svaret frå Luna i juni, ser det ut til at dette er dekka.
Flytter denne til «Avklare».
Eller skal vi berre lukke saka? @ttitland
