### ISSUE TITLE
[BRUKERHISTORIE] Skjema på nettsiden for henvending til datajegeren

### ISSUE THREAD

**Issue by ttitland** [datadeling/behov-issue-tracker#167]
Som: bruker av Datajegertjenesten
Ønsker jeg å: sende min forespørsel for datasett via skjema på nettsiden til Datafabrikken
Slik at: jeg får veiledning til å sende alle relevante opplysninger som kan gjøre det enklere for datajegeren å finne datasettet jeg trenger

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by ttitland** [comment]
Her er link til beskrivelse av tjenesten: https://digdir.sharepoint.com/:w:/r/sites/Prosjekt_Datafabrikken/Delte%20dokumenter/3.%20Tjenesteutvikling/2.%20Datafabrikkens%20tjenestetilbud/Datajegeren/Datajegeren%20-%20beskrivelse%20av%20tjenesten%20og%20digital%20f%C3%B8rstelinje.docx?d=w705c79b5739a4d5da3abffb4059dd2be&csf=1&web=1&e=6RaBKz

Det vil også komme skisser.

**Comment by livarb** [comment]
Skissene, lenke frå [tilknytt oppgåve](https://github.com/datadeling/datafabrikken-portal/issues/230): https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datahunter-d.html
Merk også at blindvegen i søk skal nemne Datajegeren.

**Comment by livarb** [comment]
No er skjemaet i staging.
Her er nokre justeringar vi vil få gjort:

a) Tekst som skal kome opp når ein sender inn skjema:
«Din forespørsel til Datajegeren er sendt. En kopi er sendt til din e-postadresse. Du vil få en e-post når en av våre datajegere starter letingen.»

b) Endre «(påkrevd)» til «(obligatorisk)».

c) Manglar eit ord i overskrifta. «Datajegeren hjelper deg finne data» --> «Datajegeren hjelper deg å finne data»

d) Nytt felt: «Vet du hvor datasettet befinner seg?». Hadde ved ein feil dotte ut frå skissa. [Skissa er oppdatert](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datahunter-d.html).

e) Endre feilmelding-tekst på obligatoriske felt. «Dette feltet er påkrevd og må fylles ut før forespørselen kan sendes.»
--> «Dette feltet er obligatorisk. Du må fylle det ut før skjemaet kan sendes inn.»
Motivasjon: Mindre formelt og stivt språk.

f) Justere tekst i e-post som går til brukaren:
f.1) Fjern «juni og». Juni er passert.
f.2) Del første avsnittet opp ved hjelp av linjeskift.
Slik er det no:
![image](https://user-images.githubusercontent.com/3617256/176880965-0c67ad12-d64f-404c-8cc7-c787f94337e9.png)
Delast opp slik som det er i Word-dokumentet:
![image](https://user-images.githubusercontent.com/3617256/176881022-1697ac49-d280-4cf9-92ed-34da0cc69292.png)

g) Sett datajegeren@norge.no på blindkopi på e-posten som går til brukaren.

h) Fjern Datajegeren frå menyen

i) Feilmelding til brukar dersom innsending av skjema feiler.
«Feil. Skjema ble ikke sendt inn. Prøv igjen senere eller kontakt oss på datajegeren@norge.no»

**Comment by livarb** [comment]
Laga sak for vidare utvikling av Datajegeren-skjema der vi kan skrive ned idear:
https://github.com/datadeling/behov-issue-tracker/issues/174
Vi plukkar opp den saka etter sommaren.

**Comment by jeffreiffers** [comment]
I tillegg til bekreftelses melding har jeg også lagt til håndtering av mulig feil ved sending av skjemaet (se skisser).

**Comment by livarb** [comment]
Har sjekka alle punkta (a–h), og det fungerer fint!

Einaste unntaket er å motta e-post frå skjemaet til datajegeren sin postboks. Vi trur at den e-posten vert filtrert vekk av Digdir sitt e-postsystem. Har sendt henvending til IT-drift (driftcrm #127614) og ser på det over helga.

Vi let skjemaet vere i staging for no. Avventar svar frå IT-drift.

**Comment by livarb** [comment]
No er skjemaet i prod. Det både ser bra ut og fungerer.
Ein må ha direktelenka for å finne det — er ikkje lenka opp frå menyen eller andre stader på nettstaden.

Vi plukkar opp tråden i august (sjå #174 ) og gjer nokre endringar før lansering.
