### ISSUE TITLE
[BRUKERHISTORIE] Nytt design og meny på forsiden

### ISSUE THREAD

**Issue by ttitland** [datadeling/behov-issue-tracker#169]
Som: prosjektleder for DP02 (produkt- og tjenesteutvikling)
Ønsker jeg å: gjøre om på menyen på nettsiden
Slik at: nye tjenester har en tilhørende menykomponent og vi har tilrettelagt for fremtidige tjenester

------------------
Her er link til beskrivelse av ny meny:

https://digdir.sharepoint.com/:w:/r/sites/Prosjekt_Datafabrikken/Delte%20dokumenter/3.%20Tjenesteutvikling/2.%20Datafabrikkens%20tjenestetilbud/Ny%20menystruktur%20p%C3%A5%20Datafabrikken.docx?d=we2abbd2c23044112a262b11463fbd399&csf=1&web=1&e=RuGbUa

Relatert til epos:

Lenke til design: [Desktop](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/home-d.html) • [Mobil](https://eggedosis.github.io/digdir/datafabrikken/redirects/design/home-m.html)
[Forsidebilde](https://drive.google.com/file/d/1Bud0Po_rlU2Um_JOeYlOBnX-T2uwGNYR/view?usp=sharing)
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by ttitland** [comment]
Tekster til bokser på forsiden:

Datalandsbyen
Still spørsmål og delta i diskusjoner

Juridisk veileder
Finn ut om datasettet kan deles

Søk etter data
Finn datasettet du trenger

Datajegeren
Få hjelp til å få tilgang på data

**Comment by oystein-asnes** [comment]
Er denne levert og akseptert @ttitland ? I så fall: kan du lukke saka?
