### ISSUE TITLE
[BRUKERHISTORIE] Lister visast ikkje rett i Datalandsbyen

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#178]
Som: bruker av Datalandsbyen i Datafabrikken
Ønsker jeg å: se poster formatert minst like bra som i Datalandsbyen.norge.no
Slik at: 

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Her er eksempel på liste i ein post som ikkje blir vist skikkeleg i Datafabrikken

https://datafabrikken.norge.no/datalandsbyen/6/ettersp%C3%B8r-datasett-og-api-er/232/sykkelparkering-i-oslo
![image](https://user-images.githubusercontent.com/3617256/189993058-3be9a69d-619d-426d-9f9a-0ee0150e4f0f.png)

Slik skal det sjå ut. Skjermbilde frå Datalandsbyen.norge.no:
![image](https://user-images.githubusercontent.com/3617256/189993204-a7827254-4477-4794-8843-e44d0a78c097.png)
https://datalandsbyen.norge.no/topic/232/sykkelparkering-i-oslo

**Comment by jeffreiffers** [comment]
http://34.117.84.181/datalandsbyen/6/ettersp%C3%B8r-datasett-og-api-er/130/sykkelparkering-i-oslo

**Comment by livarb** [comment]
Det ser bra ut. Det er ein liten ting eg lurer på om kan justerast.
Det er lite luft mellom lista og overskrifta:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/3617256/192534308-cbe23e59-d0fa-4bae-b702-cf6cca16a03e.png">

Mens i NodeBB/Datalandsbyen.norge.no er det meir luft så det ser betre ut:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/3617256/192534426-ef6548ae-ef3a-4e33-9118-26d40f2556e2.png">

**Comment by jeffreiffers** [comment]
Jeg legger til extra luft...
