### ISSUE TITLE
[BRUKERHISTORIE] Kodesnuttar visast ikkje i avgrensa boks i DF-DL

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#179]
Relatert til epos:

Ønskjer at kodesnuttar skal visast på samme måte i Datafabrikken som i NodeBB.

I Datalandsbyen.norge.no vert kodesnuttar vist i ein avgrensa boks som ein kan scrolle i.
I Datalandsbyen i Datafabrikken vert kodesnutten vist i sin fulle lengde. Det er også formatering av koden (e.g. fargar).

Eksempel på post der ein ser forskjellen (scroll ned til slutten av innlegget):
https://datalandsbyen.norge.no/topic/238/magasinstatistikk-for-norsk-kraftproduksjon
https://datafabrikken.norge.no/datalandsbyen/2/gode-eksempler-p%C3%A5-bruk/238/magasinstatistikk-for-norsk-kraftproduksjon

I Datalandsbyen.norge.no:
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/3617256/192235797-e23d29ed-bc9f-4ddb-b50c-35a9477917a0.png">

I Datafabrikken:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/3617256/192235943-a9cc2c54-eea8-47d8-9467-09f61beb0eb5.png">

**Comment by jeffreiffers** [comment]
http://34.117.84.181/datalandsbyen/2/gode-eksempler-p%C3%A5-bruk/133/magasinstatistikk​​​​​​​

**Comment by livarb** [comment]
Scroll-boksen er veldig bra! Sett noko på fargelegging ([syntax highlighting](https://en.wikipedia.org/wiki/Syntax_highlighting) som det heiter på fint)? Nemde det så vidt i beskrivelsen på denne GitHub-saka, men ser eg kunne valt ein betre tittel på saka som ikkje foreleda ein til å tru det kun gjeld å få det i ein scrollbar boks.

**Comment by livarb** [comment]
Godkjent! Lagar ny separat sak angåande syntax highlighting.
