### ISSUE TITLE
[BRUKERHISTORIE] Dele data om gjenstående materialer

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#18]
Som <byggherre> av et byggeprosjekt
ønsker jeg å dele data om gjenstående materialer
slik at jeg kan spare penger ved at andre prosjekter henter mine materialer

------------------

Relatert til epos: #13 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Lukkes til caset eventuelt aktualiseres på nytt.
