### ISSUE TITLE
[BRUKERHISTORIE] Kodesnuttar manglar syntax highlighting i Datalandsbyen

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#180]
Som:
Ønsker jeg å:
Slik at:

------------------

Relatert til: #179

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by jeffreiffers** [comment]
Bruker Prismjs (https://prismjs.com/) som standard renderer det slik:

![Screenshot from 2022-09-28 09-18-30](https://user-images.githubusercontent.com/430997/192713827-054bce58-d7d6-41dd-8eb1-c819972e8cfb.png)

**Comment by livarb** [comment]
Tykkjer det ser betre ut med ein meir vanleg fargepalett. A la den ein får på eksempelet på prismjs.com når ein vel «Default».
![image](https://user-images.githubusercontent.com/3617256/192741469-223217d7-8346-4e50-827e-78a360c73b8a.png)

**Comment by livarb** [comment]
Spurte om råd i [Kode24-klubben på Facebook](https://www.facebook.com/groups/kode24/posts/2050374928484898).
Mistenker at HighlightJS er beste alternativet, sjølv om det ikkje greier å velje rett språk.

**Comment by livarb** [comment]
Ikkje fått tips på alternativer i posten i Facebook-gruppa.
Tenker HighlightJS er beste alternativet. Ser det likt ut som i NodeBB, så er det bra nok.
Er det dette som er skrudd på i staging akkurat no?

**Comment by livarb** [comment]
Dette ser bra ut:
![image](https://user-images.githubusercontent.com/3617256/199194879-d2040319-488f-4963-965b-42abb6e7bf94.png)
https://datafabrikken.norge.no/datalandsbyen/2/gode-eksempler-p%C3%A5-bruk/238/magasinstatistikk-for-norsk-kraftproduksjon
