### ISSUE TITLE
[EPOS] Tilgang til data

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#20]
Som konsument av data
Ønsker jeg å få tilgang til data
Slik at jeg kan bruke de i min tjenesteproduksjon

------------------

Tilknyttede brukerhistorier:

Lenke til trådskisser:
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Løses av #2
