### ISSUE TITLE
[EPOS] Etterspørre data

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#21]
Som datakonsument
Ønsker jeg å etterspørre data jeg ikke finner
Slik at jeg kan vurdere om jeg kan benytte denne dataen

------------------

Tilknyttede brukerhistorier:

Lenke til trådskisser:
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Adressere dette med følgende:
- Gjøre eier klikkbar - lenke til virksomhetssiden
- Få kontaktinfo inn som en kvalitetskriterium
- Vurdere å oute de ikke har oppgitt kontaktinfo på detaljesiden

**Comment by oystein-asnes** [comment]
Denne er delvis realisert gjennom datalandsbyen og tas også inn som en del av #85
