### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til sanntidsdata

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#30]
Som Mattilsynet 
ønskjer eg tilgang til sanntidsdata
slik at vi betre kan følgje med på vannkvalitet og avvik.

------------------

Relatert til epos: #2 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Løses av mer generisk brukerhistorie

**Comment by oystein-asnes** [comment]
Lukkes. Dekkes av den mer generelle  #83
