### ISSUE TITLE
[EPOS] Standardisering av data

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#44]
Som markedsaktør som leverer programmer/systemer
Ønsker jeg en standard
Slik at effektiv og forutsigbar tilgang til data

------------------

Tilknyttede brukerhistorier:

Lenke til trådskisser:
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Eposet er veldig generelt å potensielt uendelig. Standardisering av data må skje innenfor domener.
