### ISSUE TITLE
[EPOS] Etterlyse datasett

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#5]
Som tilbyder av informasjon 
ønsker jeg å kunne etterlyse datasett som jeg ikke finner 
slik at jeg kan få informasjon om hvor jeg kan få tilgang til disse 

------------------

Tilknyttede brukerhistorier:

Lenke til trådskisser:
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Løst gjennom tjenesten https://datalandsbyen.norge.no/category/6/ettersp%C3%B8r-datasett-og-api-er
