### ISSUE TITLE
[BRUKERHISTORIE] Holde seg oppdatert på siste nytt fra datafabrikken

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#50]
Som interessent
ønsker jeg å ha mulighet til å reklamere for events, kampanjer, call to action eller samarbeid for å skape nye samarbeidskonstellasjon, 
slik at jeg kan bidra til utviklingen av datafabrikken og øke deling av data mellom ulike aktører

Som interessent
Ønsker jeg å være oppdatert om hva som skjer på datafabrikken
Slik at jeg kan engasjere meg omkring relevante aktiviteter som skjer.

#### Akseptansekriterie:
- bruker skal ha muligeht til å subscribe til datafabrikken for å få med seg nyheter og an

------------------

Relatert til epos:

Lenke til design:
https://eggedosis.github.io/digdir/datafabrikken/redirects/wireframes/home-1-d.html

Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by lillelars** [comment]
Venter med å lukke denne til denne kompoenten er på plass:
![image](https://user-images.githubusercontent.com/39513382/123050574-25d98400-d401-11eb-818b-07fd3089c1d9.png)

**Comment by lillelars** [comment]
@livarb sjekker opp med kom så ser iv hva vi får gjort i løpet av neste uke.

**Comment by livarb** [comment]
Vi rakk ikkje dette til lansering av konseptversjonen. Vi tar dette i samanheng med å legge meir detaljert kommunikasjonsplan for Datafabrikken.

**Comment by oystein-asnes** [comment]
Første del er løst gjennom datalandsbyen. Andre del (siste nytt) er levert, men abonnering på siste nytt opprettes i egen brukerhistorie.
