### ISSUE TITLE
[BRUKERHISTORIE] Oversikt over offentlige data 

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#51]
Som [operativ bruker]
ønsker jeg å raskt få oversikt over hvilke offentlige data Datafabrikken kan tilby tilgang
til slik at jeg kan vurdere om det er datasett som kan skape verdi for min organisasjon

Underhistorier:
#62 
Som [operatør] ønsker jeg raskt å få oversikt over tilgjengelige data og de best egnede data for mitt formål
Som [operatør] ønsker jeg å se hvilke tilgjengelige data som finnes innenfor "mitt domene/min bransje"
Som [operatør] ønsker jeg raskt å få trygghet i om de aktuelle data er egnet for meg eller ikke, og hvordan jeg skal få tilgang

#### Akseptansekriterier:

- [ ] Informasjonsside med introtekster til ulike datakataloger
- [ ] Datafabrikkens eget datasett-søk med tematisk inngang

------------------

Relatert til epos: #56 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Har sendt inn spørsmål til data.europa.eu om vi kan bruke ikona dei har brukt.
![image](https://user-images.githubusercontent.com/3617256/120766085-2aa1cb00-c51a-11eb-8eae-441763a56796.png)

**Comment by oystein-asnes** [comment]
Duplikat. Dekkes av #55 og #62
