### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til best practice rundt data deling 

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#54]
Som [operativ konsument]
ønsker jeg [innsikt/økt kompetanse/guide] i hvordan jeg kan få tilgang til best practice rundt data deling for å optimaliser verdien av mine data

Underhistorie:
a)Som operativ bruker ønsker jeg veiledning i bruk av data, slik at jeg bedre kan forstå mulighetene knyttet til datadrevne produkter og tjenester

b)Som operativ bruker ønsker jeg veiledning i prosessen med å få tilgang til data fra det offentlige, slik at jeg på forhånd vet hva prosessen innebærer.

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Lukkes. Realiseres gjennom #49
