### ISSUE TITLE
[BRUKERHISTORIE] Tilpasse nasjonal verktøykasse for deling av data til SMB-er og private datatilbydere

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#55]
Ansvarlig:
Helle

Som: konsument eller tilbyder av data
Ønsker jeg å: få stegvis veiledning
Slik at: jeg får hjelp til prosessen med å tilby og/eller ta i bruk data

------------------

Relatert til epos: #19 , #20 

Lenke til design:
Lenke til løsningsarkitektur: 

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Tilpasse Digdirs Nasjonale verktøykasse for deling av data: https://www.digdir.no/apne-data/nasjonal-verktoykasse-deling-av-data/2243

**Comment by helleas** [comment]
Hovedsider:
https://datafabrikken.norge.no/finn-data/datakilder
https://datafabrikken.norge.no/finn-data/veiledere-og-kompetanse
Undersider:
https://datafabrikken.norge.no/finn-data/veiledere-og-kompetanse/juridiske-rammer-bruk-av-data
https://datafabrikken.norge.no/finn-data/datakilder/privat-sektor
