### ISSUE TITLE
[EPOS] Tilgang til spesifikke datasett

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#6]
Som tilbyder av informasjon 
ønsker jeg tilgang datasett X 

------------------

Tilknyttede brukerhistorier:

Lenke til trådskisser:
Lenke til overordna arkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Lukkes. Behovet er dekket av andre epos.
