### ISSUE TITLE
[BRUKERHISTORIE] Lenker til eksisterende veiledning

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#60]
Som: datatilbyder eller datakonsument
Ønsker jeg å: få enkel tilgang til relevante veiledere
Slik at: jeg får hjelp i prosessen med å dele og ta i bruk data

------------------

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by lillelars** [comment]
Første iterasjon av eksisterende veiledning er på plass.
Flikker litt til på ulike tekster.
