### ISSUE TITLE
[BRUKERHISTORIE] Synliggjøring av datafabrikken ved google-søk

### ISSUE THREAD

**Issue by lillelars** [datadeling/behov-issue-tracker#61]
Som datafabrikken
Ønsker jeg å få vite om datafabrikken ved å benytte søkemotorer på nett
Slik at jeg får opp datafabrikken i resultatsettet

------------------

Trenger riktige beskrivelser for å bli indeksert korrekt.

Akseptansekriterie:
- ved søk på datafabrikken eller innhold datafabrikken tilbyr skal dette dukke opp i første resultatsett ved googlesøk

Relatert til epos:

Lenke til design: N/A
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Snakka med Øyvind i går og la følgande plan:
1. Livar sørger for oppdatert tittel og beskrivelse.
2. Øyvind legg inn oppdatert info og ber Google indeksere. Vi sjekkar at indekseringa er ok.
3. Ved lansering sjekkar vi at innhaldet på undersidene vert indeksert rett.

Noverande tittel og beskrivelse:
![image](https://user-images.githubusercontent.com/3617256/120309372-76176780-c2d5-11eb-93f3-7d34b9518ba9.png)
frå Facebook debugger: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdatafabrikken.norge.no%2F

**Comment by livarb** [comment]
@oyvindis : Vi kan bruke noverande tittel og beskrivelse. Kan du be Google indeksere og sjå kva tilbakemeldinga frå Google er? Reknar med ein får nokre tilbakemeldingar om ting som kan forbetrast (via Google Search Console eller noko slikt).

**Comment by livarb** [comment]
Ser nettsida no er treff nr. 8 på side 1 når ein søker på "datafabrikken": https://www.google.com/search?q=datafabrikken
![image](https://user-images.githubusercontent.com/3617256/121139392-035c3e00-c839-11eb-9df0-771ab1a9b472.png)

**Comment by livarb** [comment]
Fekk ingen treff i Google når eg søkte på "nasjonale datakatalogene" som er nemt på denne sida:
https://datafabrikken.norge.no/finn-data/datakilder    @oyvindis

**Comment by livarb** [comment]
Prata med våre fagfolk.
- Vi skal få registrert Datafabrikken i Google Search Console så vi kan sjå nærare på status hos Google der. Treng DNS-bekrefting som ein må ha hjelp av IT-drift til.
- Kan vere vi må rigge sitemap for å bli indeksert rett. Ser nærare på dette.

**Comment by oyvindis** [comment]
Vi har allerede registrert Datafabrikken i Google Search Console. https://search.google.com/search-console?resource_id=https%3A%2F%2Fdatafabrikken.norge.no%2F

Hans Olav fikser tilgang hvis du ikke allerede har det.

**Comment by livarb** [comment]
No får ein søketreff på undersidene på Datafabrikken si nettside. Bra jobba!
