### ISSUE TITLE
[BRUKERHISTORIE] Datasett-søk for datafabrikken.norge.no

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#62]
"Temasky".

Som: Næringsdrivende 
Ønsker jeg å: få et tilrettelagt søketjeneste med tematisk inngang
Slik at: jeg kan raskt og enkelt finne data på datafabrikkens nettside

Operatsjonelt:
Bruker skriver "Turer i skog og mark" i søke-feltet og trykker på tema "Friluftsliv". -> treffliste er alle i søkeresultat med tema "friluftsliv".

Bruker skriver "Turer i skog og mark" i søke-feltet og trykker på tema "Friluftsliv", og velger "json" i Format-filter. -> treffliste er alle i søkeresultat med tema "friluftsliv" _og_ format = json.

Bruker skriver "Turer i skog og mark" i søke-feltet og trykker på tema "Friluftsliv", velger "json" i Format-filter, og velger "Åpne data" i Tilgangsfilteret. -> treffliste er alle i søkeresultat med tema "friluftsliv" _og_ format = json og/eller* tilgang="åpne data".

* Om det er `and` eller `or` er gitt av bruker, se #68.

## And/or betraktninger:
Temasky er å betrakte som et filter.

- Mellom Temaskyen og Filter-kategorier skal bruker kunne velge and eller or (default `or` )
------------------

Relatert til epos: #56 
Relatert til brukerhistorie: #51 

Issues knyttet mot dette behovet:
- [ ] https://github.com/Informasjonsforvaltning/fdk-fulltext-search/issues/149

- [ ] https://github.com/Informasjonsforvaltning/fdk-fulltext-search/issues/150

Lenke til design:
https://eggedosis.github.io/digdir/datafabrikken/redirects/design/services-search-for-data-d.html

Lenke til løsningsarkitektur: Dette realiseres ved en "temasky" og spørringer mot fdk-fulltext-search API.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by livarb** [comment]
Vi kan dessverre ikkje direkte nytte ikona som den europeiske dataportalen brukar:
«Unfortunately, and after analysis, we have to inform you that the icons are from istock.com and we have the right to use it but we cannot assign right to a third party. We are sorry for that. Next time we will use open licenced icons.»

Alternativt kan ein finne fram ikona og kjøpe rett til å bruke dei: https://www.istockphoto.com/
Opprinneleg kommentar om dette på ei anna sak: https://github.com/datadeling/behov-issue-tracker/issues/51#issuecomment-854454069

**Comment by oystein-asnes** [comment]
Ok. Då veit vi det @LeneSundsbo

**Comment by oystein-asnes** [comment]
Har laget en oversikt over alle temaene (kolonne A) der jeg har kombinert de to filtrene for å være sikker på å fange opp alt.  https://docs.google.com/spreadsheets/d/1mY2lowDq7i4ibw4Ut_n3CQon-kzKn0SHg2EpUjThyGI/edit?usp=sharing 
Merk at det er 13 tema i utgangspunktet (på data.norge.no kan det se ut som det bare er 10, men det er trolig en bug). 

@oyvindis: Målet er altså at `Regioner og byer` skal inkludere de som er tagget `Bygg og eiendom`. Altså: forventet resultat = datasett med EU-tema  `Regioner og byer` ELLER Los-tema `Bygg og eiendom`. 
Se bare bort fra kolonne C-F - det er A og G som er viktig her.

Filteret ser ut til å ha en AND - funksjon mellom disse to vokabularene som jeg ikke klarer å manipulere meg rundt. 

@LeneSundsbo : Dersom tallet 13 knekker designet, kan vi vurdere å ta bort `Forvaltning og offentlig sektor`. Den står NESTEN aldri alene og tilfører derfor liten verdi.

**Comment by oystein-asnes** [comment]
En liten bug i det ene filteret, @oyvindis : https://datafabrikken.norge.no/finn-data/sok-datasett?theme=GOVI  må endres til >https://datafabrikken.norge.no/finn-data/sok-datasett?theme=GOVE  for `Forvaltning og offentlig sektor`.

Foreslår samtidig å endre spørringen for `Energi  `fra https://datafabrikken.norge.no/finn-data/sok-datasett?losTheme=natur-klima-og-miljo%2Fenergi til https://datafabrikken.norge.no/finn-data/sok-datasett?theme=ENER

**Comment by oystein-asnes** [comment]
Testet. Filteret  "begrenset tilgang"  skal ikke inkludere åpne data @oyvindis

**Comment by oyvindis** [comment]
Kan endre. 
Da blir filter "Begrenset tilgang" bare lik "ikke åpen lisens".

**Comment by oyvindis** [comment]
Endret filter "Begrense tilgang". Viser nå datasett som ikke har distribusjoner med åpen lisens.

**Comment by oystein-asnes** [comment]
Har testa og ynskjer at se ser meir på dette før vi kvitterer ut:

 - [ ] Tilgangsnivå: Mange datasett får feilaktiv status som "Ukjent". I FDK er det totalt [6 datasett som manglar klassifisering,](https://data.norge.no/datasets?accessrights=Ukjent) [men i DF er antallet ein god del høgare](https://datafabrikken.norge.no/finn-data/sok-datasett?accessRights=true). Test: følge https://datafabrikken.norge.no/finn-data/sok-datasett?theme=TRAN&accessRights=true er ikkje `ukjendt`, men `begrenset tilgang`. 
- [ ] Nullstill søk: Når eg har brukt søkefeltet er, det ingen måte å nullstille søket på, bortsett frå å legge inn nye søkestrengar. 
- [ ] Format: Når kombinasjon av format og tema gir 0 treff, så forsvinn format lista frå GUI
- [ ] Format:  XML kjem to gonger i format-lista

**Comment by oyvindis** [comment]
Pkt. 1 Rettet
Pkt. 2 Rettet

**Comment by oyvindis** [comment]
Pkt. 3 må løses ved å velge en annen strategi for visning av format. Da må man alltid vise hele format-listen basert på en referanseliste. Ulempen er at den listen blir veldig lang og også vil inneholde alle formater selv om de ikke har noen datasett koblet til seg. Dagens visning viser bare formater som er representert i resultatlisten av datasettene, men da forsvinner formatvisning hvis resultatlisten er tom.

**Comment by oystein-asnes** [comment]
Punkt 3 er ikkje kritisk funksjonalitet.  Saka kan lukkast.
