### ISSUE TITLE
Opprettelse av kostnadskonto GCP

### ISSUE THREAD

**Issue by valosnah** [datadeling/behov-issue-tracker#65]
Google Cloud for datafabrikken er satt opp med kostnadskontoen som benyttes av Felles Datakatalog (håndteres av ATEA). Da jeg antar Datafabrikken ligger under et annet prosjekt, må det gjøres en vurdering av om:

- [ ] Fakturaen kan splittes opp av Atea
- [ ] Datafabrikken må få opprettet en egen konto

**Comment by stigbd** [comment]
Sjekker.

**Comment by stigbd** [comment]
Vi kan enkelt ta ut rapporter over kostnader som er knytta til Datafabrikken i dag. Lukker derfor.
