### ISSUE TITLE
[BRUKERHISTORIE] Google Analytics

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#66]
Som: eier av datafabrikken.norge.no
Ønsker jeg å: få statistikk om bruken av mitt nettsted
Slik at: kan få innsikt hvordan den blir av hvem når.

------------------

Relatert til epos: #56 

Lenke til design:
Lenke til løsningsarkitektur: 
Løser dette ved å opprette en Google Analytics konto og legge denne id på relevant sted.

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by valosnah** [comment]
ID opprettet
