### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til sammensatte data frå kommunen

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#7]
Som tenesteutviklar,
ønskjer eg tilgang på sammensatte data (for eksempel kommunale) via eit felles grensesnitt på samme format
så eg kan tilby mine brukarar informasjon for heile Norge utan mykje manuelt arbeid. 

------------------

Relatert til epos: #6 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Lukkes. Er knyttet til konkrete case. Erstattes av generiske behovsbeskrivelser.
