### ISSUE TITLE
[BRUKERHISTORIE] Tettare integrasjon mellom Datafabrikken og Datalandsbyen

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#71]
Som: Datafabrikken
Ønsker jeg å: ha et Datafabrikken-design på Datalandsbyen
Slik at: Datalandsbyen blir tettere integrert i Datafabrikken

------------------

Relatert til epos:

Lenke til design: https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-d.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

Tankar om løysing:

1. Behalde Datafabrikken-URL
Det er positivt om ein i integrert versjon kan djuplenke til enkeltpostar.

2. Unngå hopping mellom design
Er interne lenker absolutte eller relative? For eksempel eit innlegg som lenkar til eit anna innlegg. Potensielt kan ein som brukar hoppe frå det eine designet til det andre. Dette bør ein unngå.

3. Gjere det tydeleg for brukarane at dei er på Datalandsbyen frå fleire nettsider

4. Besøksstatistikk
Vi treng besøksstatistikk som viser kor mange som les Datalandsbyen via Datafabrikken. Ikkje berre kunne sjå dei som klikkar seg vidare inn på "full-versjon" av Datalandsbyen. Kan vi sjå samla statistikk for alle besøk på Datalandsbyen, uavhengig av integrasjon?

**Comment by livarb** [comment]
La inn nytt punkt 4 om besøksstatistikk.

Tok elles vekk utdaterte innleiande tankar om løysing:
a) Header: Datafabrikken-logo og Datafabrikken-meny
b) Footer: justerast
c) Datalandsbyen-grafikk på framsida. Kan denne stilast annleis?
d) Uttrykk tilpassast Datafabrikken elles, til dømes bakgrunnsfarge

**Comment by livarb** [comment]
Frå behovsstand-up i dag:
- Lene ser på lenker til innlogging frå hhv. visning av trådar i ein kategori og visning av postane i ein enkelt tråd
- Luna tek vidare saka om besøksstatistikk til utviklarane som vurderer mogelege løysingar og kjem med anbefaling.

**Comment by livarb** [comment]
Frå stand-up:
- @LeneSundsbo ser på footer og lenke til meir info om Datalandsbyen (f.eks. "Les mer"-tekstlenke i slutten av ingressen). UU-krav skal vere oppfylt.

**Comment by livarb** [comment]
Dette ser veldig bra ut i testmiljøet!
Eit par foreløpige tilbakemeldingar:

1. Legg til punktum og mellomrom i visning av tidspunkt for post.
F.eks. "10.06.2021 kl15:16" --> "10.06.2021 kl. 15:16"
![image](https://user-images.githubusercontent.com/3617256/135147138-05a8edfd-bbef-4329-ac1f-fe2da88e3978.png)

2. Manglar det støtte for bilder i postar?
F.eks. <testmiljø>/datalandsbyen/2/gode-eksempler-og-inspirasjon/36/bergens-tidende-med-automatisk-varsling-til-journalistar

3. Mindre luft i framsida, over kategoriane
Grunna grafikken til høgre så er det unødig mellomrom mellom ingressen og kategoriane.
Nemde dette for @LeneSundsbo tidlegare. Reknar med ho vil gje innspel? Er det kanskje så enkelt som å redusere størrelsen på chat-melding-bildet?
![image](https://user-images.githubusercontent.com/3617256/135147712-596eae60-35ed-426c-a9a3-654605dc2251.png)

4. Skrivefeil i ingressen på framsida
"for å skap verdi" --> "for å skape verdi"

**Comment by livarb** [comment]
@shenluna : Skal sjå om det er fleire tilbakemeldingar på saka. Postar eventuelt fleire innspel når eg er på jobb att på fredag. Sjå elles foreløpige kommentarar over.

**Comment by shenluna** [comment]
@livarb Nå er alle punktene du har nevnt blitt fikset.

**Comment by livarb** [comment]
@shenluna Glimrande! Skal sjå på kommentarar frå andre i morgon og gje siste tilbakemelding. Nokre av dei interne innspela blir ny GitHub-sak.

**Comment by livarb** [comment]
Siste innspel på denne saka:
Knappane "Logg inn for å publisere" (inne i ein kategori) og "Logg inn for å kommentere" (inne i eit Emne) fører ein rett til brukarprofil.
1. Kan ein få desse til å føre ein direkte til hhv. kategori og tråd?
2. Namna til knappane tilsvarar det som er i Datalandsbyen når ein ikkje er innlogga. Men når ein kjem frå Datafabrikken så kan ein vere innlogga på Datalandsbyen. Foreslår kalle om til "Nytt emne" og "Skriv kommentar". Kanskje med " (krever innlogging)" på slutten? Kva tenker de @LeneSundsbo @oystein-asnes

**Comment by oystein-asnes** [comment]
> 2. Namna til knappane tilsvarar det som er i Datalandsbyen når ein ikkje er innlogga. Men når ein kjem frå Datafabrikken så kan ein vere innlogga på Datalandsbyen. Foreslår kalle om til "Nytt emne" og "Skriv kommentar". Kanskje med " (krever innlogging)" på slutten? Kva tenker de @LeneSundsbo @oystein-asnes

Ettersom datafabrikken ikkje veit om brukaren er innlogga eller ikkje (?), så er dette eit greitt kompromiss.

**Comment by oystein-asnes** [comment]
Foreslår å ta med toppmenyen: Kategorier | Emneord | Siste | Populære | Kalender |    Logg inn/Registrer (ekstern)|

**Comment by shenluna** [comment]
Integrasjonen mellom Datafabrikken og Datalandsbyen er nå prodsatt. Det som gjenstår blir løst i egne brukerhistorier. Lukker dermed denne saken.
