### ISSUE TITLE
[BRUKERHISTORIE] Optimalisering av datasett-søk på datafabrikken (og data.norge.no)

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#73]
Som bruker av datasettkatalogen ønsker jeg å få treff på datasett som er "tagget" med termen jeg benytter når jeg søker - eller et assosiert søkeord, slik at jeg finner det jeg leter etter. 

Datasett-søket ser ut til å ignorere dcat:keywords og Los. Når søkeord jeg benytter ikke er nevnt i tittel eller beskrivelse, så er resultatet null treff. 

Eksempel:  Søk på "kulturbygg" gir null treff på tross av at "Anleggsregisteret" er tagget med emneorder [Kulturbygg](https://psi.norge.no/los/ord/kulturbygg.html )

Løsningsforslag: Inkludere Los-termene (ev. med tilhørende språkvarianter og hiddenLabels) i søket

Ambisjonsnivå 1:
Treff på selve emneordene som ligger i dcat:keyword. Akseptanse-test: Søk på "kulturbygg" skal gi treff på anleggsregisteret https://data.norge.no/datasets/45e016b0-5fb2-4b6f-bd6a-84019de002cd  
 
Ambisjonsnivå 2:
Det hadde vore såå kult om vi kan utvide dette til også å inkludere a) andre språkvarianter (nn og en) og b)  HiddenLabels, jf https://psi.norge.no/los/ord/kulturbygg.html 
Akseptansetest: a) Søk på "Cultural buildings" skal gi treff på anleggsregisteret b) Søk på "galleri" gir treff på anleggsregisteret.

**Comment by shenluna** [comment]
Ambisjonsnivå 1 skal nå være fikset. Vil du ta en titt @oystein-asnes

**Comment by livarb** [comment]
Frå stand-up i dag: ønskjer å ta med ambisjonsnivå 2 inn i heilheitleg blikk på søk no etter innspel frå Joachim.
@stigbd  lagar nytt epos og lenker inn denne saka.

**Comment by oystein-asnes** [comment]
Lukkes. Ambisjonsnivå 2 er dekket av nytt issue ( #91)
