### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til kommunebeslutninger

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#8]
Som tjenesteutvikler hos en SMB 
trenger jeg tilgang til kommunebeslutninger om utviklingsplaner/areal planer.

------------------

Relatert til epos: #6 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Lukkes. Er knyttet til konkrete case. Erstattes av generiske behovsbeskrivelser.
