### ISSUE TITLE
[BRUKERHISTORIE] Lavere dropout-rate på datafabrikkens fremside

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#80]
Som: tilbyder av datafabrikkens nettsider
Ønsker jeg: at våre målgrupper skal oppleve fremsiden som relevant 
Slik at: de klikker seg videre til datafabrikkens undersider, og får dekket behovet de kom for 

------------------
Endringsforslag (fra Pål)
1)	En diskret, lett animert (altså rolig, korte bevegelser) pil som er nederst og midt på forsiden. Et enkelt design og veldig bred sett i forhold til høyden. En horisontal chevron feks. Eksempel her: https://youtu.be/lEKIsCJaR8k?t=324
2)	Endre bakgrunnsfarge på knappeelementet «Bli kjent med datafabrikken» til grønt i samme tone som resten av siden (dersom mulig, det kan fort bli veldig grellt), men uansett sørge for bedre kontrast mot bakgrunnen. Den vaskes litt ut akkurat nå.
3)	Sidene har ganske mye ledig plass i skrivende stund, og er bortimot frie for grafikk. Vi trenger en del grafiske elementer der, eventuelt noen smakfulle stockphoto (det er ikke lett å finne...), men noe som bryter opp den monotone siden. Bedre med et enkelt bilde, enn noe som er over-toppen-stockphoto. Kanskje høyre side av dette feks: https://www.pexels.com/nb-no/bilde/gang-perspektiv-database-datasenter-325229/ 

Relatert til epos: #79 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Sentrale elementer som bør fremheves på framsiden
- Finne Data
- Dele (synliggjøre) Data – (ikke en del av dagens løsning). 
- Datalandsbyen 
- Kurs og veiledning

**Comment by Den-sortesvane** [comment]
En utfordring brukertestene viste, var at det var behov for mye scrolling. Ser det samme igjen på ny side. Skulle gjerne sett ihvertfall de 3-4 første kategoriene med en gang en kommer inn i datalandsbyen.  Nå må en scrolle ned for å få dem opp og bruker får ikke oversikt raskt.
