### ISSUE TITLE
[BRUKERHISTORIE] Legge til ingressbilder for nyhetssaker

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#81]
Som: forfatter av nyheter  på datafabrikken
Ønsker jeg å: legge til ingressbilder i artiklene
Slik at: at bildet jeg velger vises på fremsiden sammen med ingress. 

------------------
Kommentar: CMS-et har et dedikert bilde for sosiale medier. Bruk dette som ingressbilde på fremsiden. Dette trenger ikke vises i selve artikkelen - her brukes bildemodulen til å plassere det samme bildet på ønsket sted i teksten. 

Relatert til epos: #79 

Lenke til design: https://eggedosis.github.io/digdir/datafabrikken/redirects/design/home-d.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by palunanue** [comment]
Har pinget Kartverket om bilder til den nyhetssaken som er der, så kan vi se på et stockphoto til den andre som allerede er der. For kommende saker som legges ut i nyhetsdrakt, er det viktig å tenke bilder tidlig når man lager sakene.
