### ISSUE TITLE
[BRUKERHISTORIE] Tilgang til API for å finne reisetid mellom to punkt

### ISSUE THREAD

**Issue by stigbd** [datadeling/behov-issue-tracker#9]
Som tenesteutviklar, 
ønskjer eg eit API for å finne reisetid mellom to punkt 
så eg kan tilby mine brukarar informasjon om kva som er innanfor pendletid frå ein eigedom.

------------------

Relatert til epos: #6 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by oystein-asnes** [comment]
Lukkes. Er knyttet til konkrete case. Erstattes av generiske behovsbeskrivelser.
