### ISSUE TITLE
[BRUKERHISTORIE] Revidere tekst på undersidene oversikt over datakilder og om datafabrikken

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#90]
Som: bruker av datafabrikken
Ønsker jeg å: få tydelig budskap på hva datafabrikken er
Slik at: forstår hva de kan tilby og får den hjelpen jeg trenger

------------------
Kommentar: Brukertesting viser at vi er utydelige på å kommunisere hva vi vil med Datafabrikken.
Relatert til epos: #79 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by Den-sortesvane** [comment]
Tekst til "om datafabrikken" sendt til Lene

**Comment by oystein-asnes** [comment]
Undersiden "oversikt over datakilder" er avpublisert. Erstattes av tematisk presentasjon. "Om datafabrikken" er oppdatert,
