### ISSUE TITLE
[BRUKERHISTORIE] Tydeligjøring av kompetanse-ressurser på nettsiden

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#92]
Som: bruker av datafabrikken
Ønsker jeg å: enkelt finne kompetanseressurser (kurs veiledere osv) på nettsiden
Slik at: jeg finner de ressursene jeg leter etter  

------------------

Relatert til epos: #79 
Må ses i sammenheng med #76 

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by Den-sortesvane** [comment]
https://norwegiancognitivecenter.com/learning <--- Link til hvordan vi kan lage en kurs-side. Kan vi ikke bare bruke dette som mal egentlig? Foreslår at vi legger inn disse syv kursene: https://digitalnorway.com/kurs/?fwp_tema=data  + Elements of AI-kurset + mulighet for å synliggjøre etterutdanningskurs fra Dscience https://www.mn.uio.no/math/studier/evu/
