### ISSUE TITLE
[BRUKERHISTORIE] Enkel navigasjon til virksomhetens egen side i datakatalogen

### ISSUE THREAD

**Issue by oystein-asnes** [datadeling/behov-issue-tracker#95]
Som: bruker av datakatalogen
Ønsker jeg å: kunne klikke på utgiver
Slik at: jeg enkelt kunne navigere fra enver enkelt ressurs (aka datasett eller datatjeneste) til virksomhetens "virksomhetsside"

------------------
Kommentar: Det er i dag ikke en egen virksomhetsside i datafabrikken. Første iterasjon er ekstern lenke til FDKs virksomhetsside. 

Relatert til epos:  #84

Lenke til design:
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by stigbd** [comment]
I første omgang vil virksomhetens virksomhetsside vere realisert av data.norge.no. Eksempel: https://data.norge.no/organizations/991825827
På sikt kan vi ta fram egen virksomhetsside i Datafabrikken viss det er ynskjeleg. (ny brukerhistorie)

**Comment by oystein-asnes** [comment]
Løst gjennmom #107
