### ISSUE TITLE
[BRUKERHISTORIE] Siste/mest populære emner i Datalandsbyen

### ISSUE THREAD

**Issue by livarb** [datadeling/behov-issue-tracker#99]
Som: bruker
Ønsker jeg å: se siste eller mest populære emner i Datalandsbyen
Slik at: jeg ser hva som rører seg i Datalandsbyen, ikke bare via Kategorier

------------------

Relatert til epos:
Bygger videre på #71 

Lenke til design: https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-d.html
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

**Comment by shenluna** [comment]
Denne kan realiseres ved å legge til menyen til Datalandsbyen
Se skisse https://eggedosis.github.io/digdir/datafabrikken/redirects/design/datalandsbyen-d.html
